[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../common", version = "*" }
env_logger = "0.11.8"
thiserror = "2.0.12"
wgpu = "25.0.2"
winit = "0.30.11"
